FROM node:lts as builder

RUN corepack enable

WORKDIR /app

COPY ./webui/package.json ./webui/yarn.lock ./

RUN yarn install

COPY ./webui .

RUN yarn build-prod
FROM nginx:stable

COPY --from=builder /app/dist /usr/share/nginx/html
