# Build stage
FROM golang:1.19.1 AS builder

WORKDIR /src/
COPY . .
RUN go build -o /app/webapi ./cmd/webapi

# Final stage
FROM debian:bookworm

WORKDIR /app/
COPY --from=builder /app/webapi ./
COPY --from=builder /src/defaultimage ./defaultimage

EXPOSE 3000

CMD ["/app/webapi"]
