FROM node:lts as builder
# workdir per il build
WORKDIR /src/
# copia cartella webui che contiene il progetto Vue.js
COPY ./webui ./webui
# sposto directory di lavoro
WORKDIR /src/webui/
# installo le dipendenze specificate nel package.json
RUN yarn install
# esegue lo script build-prod specificato nel package.json
RUN yarn run build-prod
# crea il container finale 
FROM nginx:stable
COPY --from=builder /src/webui/dist /usr/share/nginx/html